### ISSUE TITLE
Feature request: Improve session handling when a connection cannot upgrade

### ISSUE THREAD

**Issue by yoheimuta** [kuiperbelt/kuiperbelt#63]
Thanks for putting this project together.

Currently, the session when [a WebSocket upgrade process fails](https://github.com/kuiperbelt/kuiperbelt/blob/b2d8dcc007b4d061759bd93970620c4a83bc7c10/server.go#L126-L133) (see the error log below) is lingering on API servers because the close callback corresponding to the connect one isn't fired.

```
2021-10-13T05:52:17.372Z	ERROR	kuiperbelt/server.go:128	cannot upgrade	{"error": "websocket: client sent data before handshake is complete"}
```

The occasion that API servers misrecognize a WebSocket connection presence can happen for several common reasons, notably, network glitch. Although, among the reasons, I think kuiperbelt should be robust against invalid clients causing intermittent but chronic failures of upgrading the HTTP server connection to the WebSocket protocol.

For compatible use with any problematic clients, it would be nice if kuiperbelt has an optional callback like "establish" in addition to the existing "connect," "close," and "receive" callbacks. The new callback will be called [here](https://github.com/kuiperbelt/kuiperbelt/blob/master/server.go#L133) after a WebSocket upgrade is completed, which means to API servers that the new callback can share the "connect" callback's responsibility like below. This type of separation looks similar to [Nchan's hooks](https://nchan.io/#hooks-and-callbacks).

| - | connect | establish |
|--|---|---|
| as-is | [API servers are supposed to **authorize clients**, **generate session keys**, and **save session related information** if needed](https://github.com/kuiperbelt/webchat-example/blob/118afa803026223a31aba36944b8d62077f9d30b/app.psgi#L51-L80) | - |
| to-be | API servers are supposed to **authorize clients** and **generate session keys** | API servers are supposed to **save session related information** if needed |

If a new callback doesn't get an OK response, the WebSocket connection should be closed immediately.

Let me know what you think. I'm willing to create a PR once we agree on how to implement it.

**Comment by mackee** [comment]
DeepL:

I am going to agree with you about your proposal. I agree with your suggestion to add an `Establish` field in `Config.Callback` to the Config and send it if it is not empty.

For confirmation, I have written down my understanding as follows

In response to the issues raised in this issue, I have come to the following understanding.

* After a `connect callback`, an upgrade may not be possible due to client, network, etc.
* The current behavior is that an error is simply logged when an upgrade fails, leaving the callback server with unusable session information.

Your suggestion is.

* Send an `establish callback` after a `connect callback` if the upgrade succeeds.
* When the callback server receives the `establish callback`, it will recognize it as a usable session, and use it for actual communication.

I understood that.

Translated with www.DeepL.com/Translator (free version)

Original:
私はあなたの提案について賛成をします。具体的には、`Config.Callback`に`Establish`fieldををConfigに追加し、これが空でなければ送るようにればよいでしょう。

確認のため、私の理解を以下に書き出してみました。

このissueで提起されている問題に対して、私は以下のように理解しました。

* `connect callback`の後にクライアントやネットワークなどの起因でupgradeができないことがある
* 現在の挙動では、upgradeに失敗した際に単にerrorが記録され、callback server側に使用できないセッション情報が残る

あなたの提案は、

* `connect callback`の後にupgradeが成功した際に、`establish callback`を送る
* `establish callback`を受け取ったcallback serverは、それを実際に使用できるセッションであると認識し、実際に通信に用いる

と理解しました。
